### ISSUE TITLE
Wouldn't work, came up with 5 errors, had to get coaches to fix it. Do not recommend.

### ISSUE THREAD

**Issue by Bruh210** [Martinsos/arduino-lib-hc-sr04#7]

**Comment by Martinsos** [comment]
Sorry, what seems to be the problem? Other people seem to be using it successfully, nobody complained so far.

**Comment by thijstriemstra** [comment]
it works fine for me as well. I'm not sure if I'm using 4 year old version, it's showing 1.0.0 in platformio ide:

<img width="692" alt="Screenshot 2020-03-18 at 02 54 06" src="https://user-images.githubusercontent.com/305679/76917493-dafac380-68c3-11ea-9028-ef65c55be562.png">

can you bump the version nr/put out a new release?

**Comment by thijstriemstra** [comment]
It also leads to this error:

```
/Users/thijstriemstra/.platformio/lib/HCSR04_ID2968/src/HCSR04.h:24:12: note: candidate: double UltraSonicDistanceSensor::measureDistanceCm()
     double measureDistanceCm();
            ^
/Users/thijstriemstra/.platformio/lib/HCSR04_ID2968/src/HCSR04.h:24:12: note:   candidate expects 0 arguments, 1 provided
```

when using:

```c++
distance = distanceSensor.measureDistanceCm(air_temperature);
```

because it's using old code (1.0.0 and not master).

**Comment by Martinsos** [comment]
@thijstriemstra I checked https://www.arduinolibraries.info/libraries/hcsr04 and it seems the last version of library that Arduino picked up is the one 4 years old.
I made a new release now and also updated the library.properties file, so let's see what happens, I think that should make it pick up a new version of the library in a couple of hours.

**Comment by Martinsos** [comment]
Ok, new version is now up :)!

Since I don't know what are those 5 errors, I will close this issue, but @Bruh210 feel free to reopen it if you can provide more detailed information regarding the errors.
