### ISSUE TITLE
Catalina 10.15.14 Issue

### ISSUE THREAD

**Issue by KovaZg** [Martinsos/arduino-lib-hc-sr04#9]
Tried to use this library, I get:
exit status 1
Error compiling for board Arduino Mega or Mega 2560.

Is there any solution?

**Comment by Martinsos** [comment]
Hi Tomislav!
Hmm, is there any more information -> could you try to obtain exact error?
This way it is really hard to figure out what is the problem.

**Comment by KovaZg** [comment]
Thanks for reply, here is my complete, unedited error message:

"Arduino: 1.8.12 (Mac OS X), Board: "Arduino Mega or Mega 2560, ATmega2560 (Mega 2560)"

/Applications/Arduino.app/Contents/Java/arduino-builder -dump-prefs -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/kova/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/kova/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/kova/Documents/Arduino/libraries -fqbn=arduino:avr:mega:cpu=atmega2560 -vid-pid=0000_0000 -ide-version=10812 -build-path /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679 -warnings=all -build-cache /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_cache_290981 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/kova/Documents/Arduino/Ultrasonic-withLibrary/Ultrasonic-withLibrary.ino
/Applications/Arduino.app/Contents/Java/arduino-builder -compile -logger=machine -hardware /Applications/Arduino.app/Contents/Java/hardware -hardware /Users/kova/Library/Arduino15/packages -tools /Applications/Arduino.app/Contents/Java/tools-builder -tools /Applications/Arduino.app/Contents/Java/hardware/tools/avr -tools /Users/kova/Library/Arduino15/packages -built-in-libraries /Applications/Arduino.app/Contents/Java/libraries -libraries /Users/kova/Documents/Arduino/libraries -fqbn=arduino:avr:mega:cpu=atmega2560 -vid-pid=0000_0000 -ide-version=10812 -build-path /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679 -warnings=all -build-cache /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_cache_290981 -prefs=build.warn_data_percentage=75 -prefs=runtime.tools.arduinoOTA.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.arduinoOTA-1.3.0.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avr-gcc-7.3.0-atmel3.6.1-arduino5.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -prefs=runtime.tools.avrdude-6.3.0-arduino17.path=/Applications/Arduino.app/Contents/Java/hardware/tools/avr -verbose /Users/kova/Documents/Arduino/Ultrasonic-withLibrary/Ultrasonic-withLibrary.ino
Using board 'mega' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Using core 'arduino' from platform in folder: /Applications/Arduino.app/Contents/Java/hardware/arduino/avr
Detecting libraries used...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/mega /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp -o /dev/null
Alternatives for HCSR04.h: [HCSR04-1.1.0@1.1.0]
ResolveLibrary(HCSR04.h)
  -> candidates: [HCSR04-1.1.0@1.1.0]
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/mega -I/Users/kova/Documents/Arduino/libraries/HCSR04-1.1.0/src /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp -o /dev/null
Using cached library dependencies for file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp
Using cached library dependencies for file: /Users/kova/Documents/Arduino/libraries/HCSR04-1.1.0/src/HCSR04.cpp
Generating function prototypes...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -w -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -flto -w -x c++ -E -CC -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/mega -I/Users/kova/Documents/Arduino/libraries/HCSR04-1.1.0/src /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp -o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/preproc/ctags_target_for_gcc_minus_e.cpp
/Applications/Arduino.app/Contents/Java/tools-builder/ctags/5.8-arduino11/ctags -u --language-force=c++ -f - --c++-kinds=svpf --fields=KSTtzns --line-directives /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/preproc/ctags_target_for_gcc_minus_e.cpp
Compiling sketch...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-g++ -c -g -Os -Wall -Wextra -std=gnu++11 -fpermissive -fno-exceptions -ffunction-sections -fdata-sections -fno-threadsafe-statics -Wno-error=narrowing -MMD -flto -mmcu=atmega2560 -DF_CPU=16000000L -DARDUINO=10812 -DARDUINO_AVR_MEGA2560 -DARDUINO_ARCH_AVR -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/cores/arduino -I/Applications/Arduino.app/Contents/Java/hardware/arduino/avr/variants/mega -I/Users/kova/Documents/Arduino/libraries/HCSR04-1.1.0/src /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp -o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o
Compiling libraries...
Compiling library "HCSR04-1.1.0"
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o
Compiling core...
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring_pulse.S.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring_pulse.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/hooks.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring_digital.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring_shift.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/WInterrupts.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/wiring_analog.c.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/CDC.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/PluggableUSB.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/HardwareSerial1.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/HardwareSerial0.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/HardwareSerial3.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/Print.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/Tone.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/WMath.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/abi.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/USBCore.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/IPAddress.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/new.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/WString.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/HardwareSerial2.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/main.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/Stream.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/HardwareSerial.cpp.o
Using previously compiled file: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/core.a
Archiving built core (caching) in: /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_cache_290981/core/core_arduino_avr_mega_cpu_atmega2560_51f02b7210b938436b779d1c032618e1.a
Linking everything together...
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/avr-gcc -Wall -Wextra -Os -g -flto -fuse-linker-plugin -Wl,--gc-sections,--relax -mmcu=atmega2560 -o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/Ultrasonic-withLibrary.ino.elf /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/Ultrasonic-withLibrary.ino.cpp.o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o /var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/core/core.a -L/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679 -lm
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o (symbol from plugin): In function `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)':
(.text+0x0): multiple definition of `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)'
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o (symbol from plugin):(.text+0x0): first defined here
/Applications/Arduino.app/Contents/Java/hardware/tools/avr/bin/../lib/gcc/avr/7.3.0/../../../../avr/bin/ld: Disabling relaxation: it will not work with multiple definitions
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o (symbol from plugin): In function `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)':
(.text+0x0): multiple definition of `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)'
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o (symbol from plugin):(.text+0x0): first defined here
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o (symbol from plugin): In function `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)':
(.text+0x0): multiple definition of `UltraSonicDistanceSensor::measureDistanceCm(float)'
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o (symbol from plugin):(.text+0x0): first defined here
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/libraries/HCSR04-1.1.0/HCSR04.cpp.o (symbol from plugin): In function `UltraSonicDistanceSensor::UltraSonicDistanceSensor(int, int)':
(.text+0x0): multiple definition of `UltraSonicDistanceSensor::measureDistanceCm()'
/var/folders/hn/kqqsl3596x98pdw5ln3qp8qr0000gn/T/arduino_build_415679/sketch/HCSR04.cpp.o (symbol from plugin):(.text+0x0): first defined here
collect2: error: ld returned 1 exit status
Using library HCSR04-1.1.0 at version 1.1.0 in folder: /Users/kova/Documents/Arduino/libraries/HCSR04-1.1.0 
exit status 1
Error compiling for board Arduino Mega or Mega 2560."

**Comment by Martinsos** [comment]
Aha, so this seems to be a Mac issue? Hmm, unfortunately I don't have Mac
to test with + nor do I have arduino at the moment to test with :D. so if
you want to pursue this further and try to figure out the problem I can
help but you will have to drive it. If not let's close the issue for now.
No problem / Molim :)!

**Comment by KovaZg** [comment]
No worries, I have Windows as well on MAC and on PC, so I got it working
there, thank you very much.

**Comment by Tamil-99** [comment]
> Tried to use this library, I get: exit status 1 Error compiling for board Arduino Mega or Mega 2560.
> 
> Is there any solution?

Chane the board setting in the tools>board>ESP8266
